#!/usr/bin/env python3
# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate one full-coverage backend conf per vendor.

Every vendor conf lists the *same* op set -- the authoritative list of ops
torch_fl generates wrappers for -- so operator support is countable by reading
one file per platform instead of diffing sparse configs against each other.

Each op maps to exactly one of five keys:

    flaggems_cpp   FlagGems C++ path (liboperators.so), Backend::kFlagGemsCpp
    flaggems       FlagGems Python/Triton path, Backend::kFlagGems
    tileops        TileOps Python shim path, Backend::kTileOps
    <vendor>       vendor-native kernel (musa, ascend, gcu, metax, ...)
    none           no accelerated impl on this platform -> cpu_fallback

Routing priority is FlagGems-first, tileops as an intermediate Python path,
vendor-native as the fallback for what neither covers, and `none` for ops
with no accelerated implementation:

    flaggems_cpp > flaggems > tileops > <vendor> > none

`flaggems_cpp` is only emitted for the confs a FLAGGEMS_KERNEL=ON build selects
(see FLAGGEMS_CPP_PLATFORMS); everywhere else those ops take the Python path to
the same kernels, because the C++ dispatcher slot is not compiled in.

`tileops` routes to Backend::kTileOps, which calls into
torch_fl.tileops.generated.shims via CallPythonOp_Generic. The 60 ops that
have a TileOps shim implementation are inlined in TILEOPS_OPS below.

`none` is recorded explicitly rather than by omission. That is the whole point
of the full-coverage shape: "absent from the file" and "known to be
unsupported" used to look identical, which made support impossible to count
and let sparse confs rot silently against a growing codegen. Omission is not
even a safe way to say "unsupported" -- GetBackendForOp() returns kFlagGemsCpp on a
table miss, so an unlisted op claims a FlagGems kernel by default.

What the file may claim is bounded by what the platform registers on
PrivateUse1. FlagGems coverage is measured on CUDA and is only a ceiling: an op
this platform does not register cannot reach any kernel, FlagGems included, so
it is written `none`. Registration sets are read from the generated
`*_register.inc` files that csrc/aten/register.cc includes -- the same list the
compiler sees -- which is why only platforms whose registration is a subset of
the op list get a generated conf. See VENDORS.

Usage:
    python3 scripts/gen_vendor_confs.py            # rewrite vendor confs
    python3 scripts/gen_vendor_confs.py --check     # exit 1 if any is stale
    python3 scripts/gen_vendor_confs.py --stats     # print a coverage table
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONF_DIR = REPO_ROOT / "torch_fl/configs"

# tests/unit/test_gen_vendor_confs.py loads this file by path (scripts/ is not an
# importable package), so a bare `import backend_coverage` would not resolve.
sys.path.insert(0, str(Path(__file__).resolve().parent))

# The op list every vendor conf must cover. backends_cuda.conf is regenerated by
# codegen_ops.py with one line per generated wrapper, so it is the authoritative
# enumeration of what torch_fl can route at all.
OP_LIST_SOURCE = "backends_cuda.conf"

# Where the backend coverage sets come from. These used to be three shared conf
# files (backends_flaggems.conf, backends_flaggems_cpp.conf, backends_tileops.conf)
# that torch_fl/configs/ carried purely as generator input -- they routed nothing
# on their own and no platform selected them. They are now data in
# scripts/backend_coverage.py, so torch_fl/configs/ holds exactly one conf per
# platform and nothing else.
from backend_coverage import (  # noqa: E402
    FLAGGEMS_CPP_OPS,
    FLAGGEMS_PYTHON_OPS,
    TILEOPS_OPS,
)

# Vendors that get a full-coverage conf.
#
# Only a platform whose PrivateUse1 registration is a *subset* of the op list
# belongs here, because that is what makes `none` honest. Claiming an op on
# PrivateUse1 with no kernel behind it does not fall back -- the call reaches the
# dispatcher and raises on the empty slot -- whereas leaving it unregistered lets
# it box to cpu_fallback. So `none` means cpu_fallback only where registration
# skips the op, and these three platforms are the ones that skip:
#
#   platform  registration branch in csrc/aten/register.cc   m.impl count
#   musa      musa_register.inc + musa_flaggems_register.inc  158
#   gcu       gcu_register.inc                                 152
#   ascend    ascend_register.inc                              372
#
# metax, tsingmicro and dcu fall through to the `#else` branch and register the
# full generated list (~2034), so a `none` entry there would be a guaranteed
# raise rather than a fallback. metax and dcu are handled as CUDA-boxing
# platforms below (see BOXING_PLATFORMS); backends_tsingmicro.conf stays
# hand-written.
#
#   vendor -> (conf naming its native kernels, other .inc files it registers)
#
# The sets are read from the generated C++ rather than from the conf this script
# rewrites, so there is no round trip to survive: registration and routing are
# derived from the same artifact the compiler sees.
VENDORS = {
    "musa": (
        "backends/musa/generated/musa_register.inc",
        ("backends/musa/generated/musa_flaggems_register.inc",),
    ),
    "gcu": ("backends/gcu/generated/gcu_register.inc", ()),
    "ascend": ("backends/ascend/generated/ascend_register.inc", ()),
}

# Ops a vendor registers straight from register.cc instead of its .inc, so they
# are invisible to the .inc scan. Ascend claims aten::matmul (and the
# matmul_backward the derivative then binds to) on PrivateUse1 under
# `#if defined(USE_ASCEND)` so the call hits the fused aclnnMatmul rather than
# decomposing into mm/bmm/view; WrapperMatmul reads this conf to decide, so the
# entry has to be here or the fused kernel is unreachable.
EXTRA_NATIVE = {"ascend": {"matmul", "matmul_backward"}}

# CUDA-boxing platforms use the same four-key shape. Their fallback kernel is the
# CUDA boxing kernel, so the `<vendor>` slot is spelled "cuda" and it covers
# every op -- which is why a boxing conf has no `none` entries while a
# native-kernel vendor has many.
#
#   platform -> (fallback backend key, conf naming that platform's triton gaps)
#
# The gap set is per-platform, not a FlagGems defect: the kernel works elsewhere,
# but this platform's triton backend cannot run it, so the op is forced back to
# boxing. Those sets live in codegen_ops.py (flaggems_forced_cuda plus the
# per-platform additions) and are recovered here by diffing that platform's
# existing conf against backends_flaggems.conf, rather than restated -- one
# source of truth, and the per-op diagnosis stays in the codegen comments.
BOXING_PLATFORMS = {
    "metax": "backends_metax.conf",
    "dcu": "backends_dcu.conf",
}
BOXING_FALLBACK = "cuda"

# Where the registration .inc files live, relative to the repo root.
CSRC_DIR = REPO_ROOT / "csrc/aten"

# Which generated confs may route to `flaggems_cpp` at all.
#
# That slot is Backend::kFlagGemsCpp, registered in csrc/aten/flaggems_cpp_kernels.cc
# behind `#ifdef FLAGOS_FLAGGEMS_CPP`, which csrc/CMakeLists.txt defines only for
# a FLAGGEMS_KERNEL=ON build -- and CMakeLists.txt force-sets FLAGGEMS_KERNEL OFF
# for ascend, dcu, musa, bpu, tsingmicro and non-boxing metax, because the path
# needs FlagGems' liboperators.so built for that vendor.
#
# One platform now means one conf, so a conf can no longer be reserved for the
# opt-in build that compiles the slot: backends_metax.conf is what every MetaX
# build reads, with or without FLAGGEMS_KERNEL=ON. The key stays legal there
# because Dispatcher::GetFn (csrc/aten/dispatcher.h) degrades kFlagGemsCpp to the
# boxing kernel when the slot is empty, instead of raising "backend not
# registered". So the 17 measured C++ routes are used when a MACA-built FlagGems
# is present and silently box when it is not -- one file, both builds.
#
# The native-kernel vendors (musa/gcu/ascend) still withhold the key. Not for
# safety, but because it would be noise: FlagGems' C++ runtime is not built for
# any of them, so every entry would degrade, and `flaggems` records the same
# routing decision honestly. Every op in the C++ set is also in the Python set
# (test_flaggems_cpp_set_is_a_subset_of_the_python_set pins that), so they reach
# the same kernel through python_op_caller; only the GIL-free entry point
# differs. (backends_flaggems_cpp.conf, the generic CUDA one, is codegen output
# and not written here.)
FLAGGEMS_CPP_PLATFORMS = {"metax"}

# Native Ascend wheels deliberately disable FLAGGEMS_PYTHON: the CI image does
# not ship Triton/FlagGems, and set_env_ascend.sh sets FLAGGEMS_PYTHON=0. Keep
# the generated conf honest by not routing Ascend through a dispatcher slot that
# is absent from the wheel. Boxing platforms compile the Python caller and may
# use the measured FlagGems coverage.
FLAGGEMS_PYTHON_PLATFORMS = {"ascend", "metax", "dcu", "gcu", "musa"}

# Platforms whose build can compile the TileOPs slot (Backend::kTileOps). The
# shims are Triton kernels needing an SM90 device plus the `tileops` package, and
# setup.py force-sets TILEOPS_KERNEL=OFF for every ACCELERATOR != "cuda" -- so on
# any other platform the slot is empty, Dispatcher::GetFn degrades kTileOps to
# cuda_fn_, and on a native-kernel vendor that is empty too. Naming `tileops` in
# those confs would therefore route a real op at nothing, which is the "backend
# not registered" class of failure this full-coverage rework exists to remove.
# No shipped conf is generated for plain cuda (codegen_ops.py writes
# backends_cuda.conf), so this is currently empty and the key reaches confs only
# through the `# tileops` annotation that FLAGOS_USE_TILEOPS reads.
TILEOPS_PLATFORMS = set()

# The 17 FlagGems C++ ops verified on MetaX hardware (of the 18 in the shared C++
# set). `mm` is the omission and is deliberate: gems' `mm` passes a SPLIT_K kwarg
# triton-metax rejects, so it stays on the boxing kernel. Recorded here because
# the conf that used to hold this measurement no longer exists separately; see
# boxing_cpp_ops(). test_metax_conf_keeps_mm_boxed pins the exception.
METAX_CPP_MEASURED = {
    "_softmax",
    "_softmax_backward_data",
    "addmm",
    "addmm.out",
    "argmax",
    "bmm",
    "bmm.out",
    "embedding",
    "max",
    "max.dim",
    "nonzero",
    "sort",
    "sort.stable",
    "sum",
    "sum.dim_IntList",
    "topk",
    "zeros",
}

LICENSE = """\
# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""


def parse_conf(path: Path) -> dict:
    """Parse `op = backend` lines. Ignores comments, blanks and `include`."""
    table = {}
    if not path.exists():
        return table
    for line in path.read_text().splitlines():
        line = line.split("#")[0].strip()
        if not line or "=" not in line:
            continue
        op, backend = line.split("=", 1)
        op, backend = op.strip(), backend.strip()
        if op and backend:
            table[op] = backend
    return table


def flaggems_python_ops(conf_dir: Path = None) -> set:
    """Ops FlagGems covers through its Python/Triton path (Backend::kFlagGems).

    `conf_dir` is accepted and ignored: this used to parse the `flagos_python`
    entries out of backends_flaggems.conf. That file existed only to carry this
    set, so it is now data (see backend_coverage.py) and the argument is kept so
    callers do not all have to change at once.
    """
    return set(FLAGGEMS_PYTHON_OPS)


def flaggems_cpp_ops(conf_dir: Path = None) -> set:
    """Ops FlagGems covers through its C++ runtime (liboperators.so, kFlagGemsCpp).

    Same story as flaggems_python_ops(): formerly the `flagos` entries of
    backends_flaggems_cpp.conf, now data.
    """
    return set(FLAGGEMS_CPP_OPS)


def tileops_ops(conf_dir: Path = None) -> set:
    """Ops with a TileOps shim behind them (Backend::kTileOps).

    Formerly the `tileops` entries of backends_tileops.conf, which was otherwise
    a copy of backends_cuda.conf. scripts/codegen_tileops.py generates both the
    shims and this set.
    """
    return set(TILEOPS_OPS)


def registered_impls(inc_path: Path) -> set:
    """Ops an `.inc` file claims on PrivateUse1, read from its `m.impl("op", ...)`.

    These files are codegen output included by csrc/aten/register.cc, so this is
    the same list the compiler sees -- the authoritative answer to "is this op
    registered on this platform", which is what decides whether `none` boxes to
    CPU or raises.
    """
    if not inc_path.exists():
        return set()
    return set(re.findall(r'm\.impl\(\s*"([^"]+)"', inc_path.read_text()))


def vendor_native_ops(vendor: str) -> set:
    """Ops with a vendor-native kernel, read from that vendor's own `.inc`.

    Earlier this was recovered from the conf being rewritten, which needed a
    trailing `# <vendor>` annotation to survive the round trip. Reading the
    generated C++ instead removes that dependency: the kernel set cannot drift
    from what is compiled, and a conf edit cannot invent or lose a kernel.

    The annotation is still *emitted* -- it is what tells a reader (and
    ALL_USE_VENDOR) that a kernel exists behind an op FlagGems currently wins.
    """
    native_inc, _ = VENDORS[vendor]
    return registered_impls(CSRC_DIR / native_inc) | EXTRA_NATIVE.get(vendor, set())


def vendor_registered_ops(vendor: str) -> set:
    """Every op this vendor claims on PrivateUse1, native kernel or FlagGems.

    MUSA registers a second file (musa_flaggems_register.inc) whose wrappers go
    through the conf-driven dispatcher to the FlagGems Python slot, so those ops
    are registered without being native kernels. Anything outside this set is
    unregistered and therefore genuinely reaches cpu_fallback.
    """
    native_inc, extra_incs = VENDORS[vendor]
    ops = registered_impls(CSRC_DIR / native_inc)
    for inc in extra_incs:
        ops |= registered_impls(CSRC_DIR / inc)
    return ops | EXTRA_NATIVE.get(vendor, set())


def boxing_triton_gaps(conf_dir: Path, filename: str, fg_py: set, fg_cpp: set) -> set:
    """Ops a boxing platform must keep on CUDA even though FlagGems covers them.

    Recovered by diffing the platform's existing conf against the shared FlagGems
    sources: an op that FlagGems covers but this conf routes to `cuda` is a
    deliberate per-platform triton gap (MetaX Xnack/ATU faults, DCU hcu VMFault
    and the missing div_rn lowering -- diagnosed per op in codegen_ops.py). This
    reads the file it later rewrites, so the gap set has to survive the round
    trip; it does, because a gap stays spelled `cuda` in the generated conf.
    """
    table = parse_conf(conf_dir / filename)
    covered = fg_py | fg_cpp
    return {op for op, backend in table.items() if backend == "cuda" and op in covered}


def boxing_cpp_ops(conf_dir: Path, filename: str, fg_cpp: set) -> set:
    """Which FlagGems C++ ops a boxing platform actually routes to that path.

    Per-platform measured, not shared: MetaX verified 17 of the 18 ops on-device
    and keeps `mm` on the boxing kernel, because gems' `mm` passes a SPLIT_K
    kwarg triton-metax rejects. That exception is the reason this set is spelled
    out here rather than derived as `fg_cpp` -- re-deriving all 18 would silently
    promote `mm` to a route that raises on the first call.

    Stated as a literal because it can no longer be recovered by reading the file
    this rewrites. One platform means one conf now, so the measurement's former
    home (backends_metax_flaggems_cpp.conf) is gone, and a conf that carries both
    the C++ and non-C++ routings cannot be diffed back into its two inputs.
    Intersected with `fg_cpp` so an op dropped from the FlagGems C++ set cannot
    linger here.
    """
    return METAX_CPP_MEASURED & fg_cpp if filename == "backends_metax.conf" else set()


def route_boxing(op: str, fg_cpp: set, fg_py: set, gaps: set, tileops: set = ()) -> str:
    """Pick the backend key for one op on a CUDA-boxing platform.

    Same priority as a native vendor, with `cuda` in the `<vendor>` slot. Boxing
    reuses the CUDA kernels wholesale, so every op has an impl and `none` never
    appears -- the difference from a native-kernel vendor is coverage, not shape.

    A triton gap outranks every accelerated key, `tileops` included: the gap is a
    measured statement that this platform's triton backend cannot run the kernel,
    and the TileOps shims are Triton-generated too.
    """
    if op in gaps:
        return BOXING_FALLBACK
    if op in fg_cpp:
        return "flaggems_cpp"
    if op in fg_py:
        return "flaggems"
    if op in tileops:
        return "tileops"
    return BOXING_FALLBACK


def route(
    op: str,
    vendor: str,
    fg_cpp: set,
    fg_py: set,
    native: set,
    registered: set,
    tileops: set = (),
) -> str:
    """Pick the backend key for one op. FlagGems first, vendor as fallback.

    `fg_py` / `fg_cpp` / `tileops` are coverage sets measured on CUDA, so they
    are a *ceiling*, not this platform's routing set. An op only routes to an
    accelerated key if the platform also registers it on PrivateUse1: those
    wrappers are reached through the op's PrivateUse1 registration, so routing an
    unregistered op to `flaggems` names a kernel no call can arrive at, and the
    op silently boxes to CPU while the conf claims coverage. Gating on
    `registered` is what keeps the file's counts true.

    `tileops` sits below both FlagGems paths and above the vendor kernel. Below
    FlagGems because FlagGems is the broader, longer-measured library and its
    routes are the ones the per-platform gap sets are calibrated against; above
    the vendor kernel because the TileOps shims are the newer path being brought
    up, so where both exist the shim is what a run should exercise. The vendor
    kernel stays reachable through the `# <vendor>` annotation and ALL_USE_VENDOR.

    An op the vendor implements but FlagGems or TileOps wins gets a trailing
    `# <vendor>` annotation. That is what tells a reader a kernel exists behind
    the winning route, and what makes ALL_USE_VENDOR able to move the op.
    """
    if op not in registered:
        return "none"
    if op in fg_cpp:
        return f"flaggems_cpp  # {vendor}" if op in native else "flaggems_cpp"
    if op in fg_py:
        return f"flaggems  # {vendor}" if op in native else "flaggems"
    if op in tileops:
        return f"tileops  # {vendor}" if op in native else "tileops"
    if op in native:
        return vendor
    return "none"


def render(platform: str, vendor: str, routes: dict, boxing: bool = False) -> str:
    """Build the conf text for one platform.

    `platform` names the conf (backends_<platform>.conf); `vendor` is the key in
    the third slot -- a native kernel name, or "cuda" for a boxing platform.
    """
    counts = {}
    for value in routes.values():
        backend = value.split("#", 1)[0].strip()
        counts[backend] = counts.get(backend, 0) + 1
    total = len(routes)
    covered = total - counts.get("none", 0)

    if boxing:
        vendor_desc = "CUDA boxing kernel (this platform is CUDA-compatible)"
    else:
        vendor_desc = "vendor-native kernel"

    lines = [LICENSE.rstrip("\n"), ""]
    lines += [
        f"# flagos op backend config for {platform} -- AUTO-GENERATED.",
        "# Regenerated by scripts/gen_vendor_confs.py -- do not edit manually.",
        "#",
        "# Full-coverage config: every op torch_fl can route is listed exactly",
        "# once, so operator support for this platform is countable from this",
        "# file alone.",
        "#",
        "# Values:",
        "#   flaggems_cpp  FlagGems C++ runtime (liboperators.so)",
        "#   flaggems      FlagGems Python/Triton path",
        "#   tileops       TileOPs Triton shims (needs TILEOPS_KERNEL=ON + SM90)",
        f"#   {vendor:<13} {vendor_desc}",
    ]
    if boxing:
        lines += [
            "#",
            f"# Routing priority: flaggems_cpp > flaggems > tileops > {vendor}.",
            "# Boxing reuses the CUDA kernels for every op, so nothing routes to",
            "# 'none' here.",
            "#",
        ]
    else:
        lines += [
            "#   none          no accelerated impl here -> reaches cpu_fallback",
            "#",
            f"# Routing priority: flaggems_cpp > flaggems > tileops > {vendor} > none.",
            "#",
        ]
    lines += [
        f"# Coverage: {covered}/{total} ops accelerated "
        f"({100.0 * covered / total:.1f}%)",
    ]
    for backend in ("flaggems_cpp", "flaggems", "tileops", vendor, "none"):
        if backend in counts:
            lines.append(f"#   {backend:<13} {counts[backend]:>5}")
    lines += [
        "#",
        "# Override one op at runtime with FLAGOS_OP_<name>=<backend> (dots in",
        "# the op name become double underscores: FLAGOS_OP_mm__out=flaggems).",
        "# Collapse the whole table onto one backend for A/B measurement with",
        "# ALL_USE_FLAGGEMS=1 or ALL_USE_VENDOR=1 (mutually exclusive). An op",
        "# only moves if that backend implements it -- known from the routed",
        "# value plus its `# <backend>` annotation. The rest are reported on",
        "# stderr and stay as configured, so ALL_USE_VENDOR is partial by",
        "# nature: a vendor implements far fewer ops than FlagGems.",
        "",
    ]
    for op in sorted(routes):
        lines.append(f"{op} = {routes[op]}")
    return "\n".join(lines) + "\n"


def build_all(conf_dir: Path) -> dict:
    """Compute {platform: (conf_text, routes, vendor_key)} for every platform.

    Covers both native-kernel vendors and CUDA-boxing platforms: same five keys,
    same priority, differing only in what sits in the vendor slot.
    """
    all_ops = set(parse_conf(conf_dir / OP_LIST_SOURCE))
    if not all_ops:
        raise SystemExit(
            f"error: no ops found in {conf_dir / OP_LIST_SOURCE}; "
            "run scripts/codegen_ops.py first"
        )

    fg_py = flaggems_python_ops(conf_dir)
    fg_cpp = flaggems_cpp_ops(conf_dir)
    tileops = tileops_ops(conf_dir)

    natives = {vendor: vendor_native_ops(vendor) for vendor in VENDORS}
    registered = {vendor: vendor_registered_ops(vendor) for vendor in VENDORS}

    # A vendor kernel can exist for an op with no entry in the CUDA-derived op
    # list (Ascend's fused matmul, claimed straight from register.cc). Dropping
    # it would silently un-route a working kernel -- and for matmul it would make
    # the aclnn path unreachable, since WrapperMatmul consults this conf. Widen
    # the list instead; the union keeps every platform's table over the same op
    # set, which is what makes coverage comparable across files.
    extra = set().union(*natives.values()) - all_ops if natives else set()
    if extra:
        print(
            f"note: {len(extra)} vendor-only op(s) added to the op list: "
            f"{', '.join(sorted(extra))}",
            file=sys.stderr,
        )
        all_ops |= extra

    out = {}
    for vendor in VENDORS:
        # A vendor build is FLAGGEMS_KERNEL=OFF, so the flaggems_cpp slot has no
        # kernel -- withhold the key and let those ops take the Python path.
        cpp_here = fg_cpp if vendor in FLAGGEMS_CPP_PLATFORMS else set()
        py_here = fg_py if vendor in FLAGGEMS_PYTHON_PLATFORMS else set()
        tileops_here = tileops if vendor in TILEOPS_PLATFORMS else set()
        routes = {
            op: route(
                op,
                vendor,
                cpp_here,
                py_here,
                natives[vendor],
                registered[vendor],
                tileops_here,
            )
            for op in sorted(all_ops)
        }
        out[vendor] = (render(vendor, vendor, routes), routes, vendor)

    for platform, sparse_conf in BOXING_PLATFORMS.items():
        gaps = boxing_triton_gaps(conf_dir, sparse_conf, fg_py, fg_cpp)
        # Only the C++-runtime conf routes to flaggems_cpp; elsewhere the slot is
        # unused and every C++ op is reached through the Python path instead.
        cpp_here = (
            boxing_cpp_ops(conf_dir, sparse_conf, fg_cpp)
            if platform in FLAGGEMS_CPP_PLATFORMS
            else set()
        )
        tileops_here = tileops if platform in TILEOPS_PLATFORMS else set()
        routes = {
            op: route_boxing(op, cpp_here, fg_py, gaps, tileops_here)
            for op in sorted(all_ops)
        }
        out[platform] = (
            render(platform, BOXING_FALLBACK, routes, boxing=True),
            routes,
            BOXING_FALLBACK,
        )
    return out


def print_stats(built: dict) -> None:
    platforms = sorted(built)
    total = len(next(iter(built.values()))[1])
    print(f"op list: {total} ops\n")
    print(
        "'native routed' counts ops that end up on the vendor kernel; ops the\n"
        "vendor also implements but that FlagGems covers are routed to FlagGems\n"
        "by priority and counted in 'kernels' only.\n"
    )
    header = (
        f"{'platform':<20} {'flaggems_cpp':>12} {'flaggems':>9} "
        f"{'vendor routed':>14} {'kernels':>8} {'none':>6} {'covered':>13}"
    )
    print(header)
    print("-" * len(header))
    for platform in platforms:
        _, routes, vendor = built[platform]
        counts = {}
        kernels = 0
        for value in routes.values():
            backend, _, annotation = value.partition("#")
            backend = backend.strip()
            counts[backend] = counts.get(backend, 0) + 1
            if backend == vendor or annotation.strip() == vendor:
                kernels += 1
        none = counts.get("none", 0)
        covered = total - none
        print(
            f"{platform:<20} {counts.get('flaggems_cpp', 0):>12} "
            f"{counts.get('flaggems', 0):>9} {counts.get(vendor, 0):>14} "
            f"{kernels:>8} {none:>6} "
            f"{covered:>6} ({100.0 * covered / total:>2.0f}%)"
        )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify the confs on disk match what would be generated",
    )
    ap.add_argument(
        "--stats", action="store_true", help="print a coverage table and exit"
    )
    args = ap.parse_args()

    built = build_all(CONF_DIR)

    if args.stats:
        print_stats(built)
        return 0

    stale = []
    for platform, (text, _, _) in sorted(built.items()):
        path = CONF_DIR / f"backends_{platform}.conf"
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path.name)
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if args.check:
        if stale:
            print(
                "error: stale vendor conf(s): "
                + ", ".join(stale)
                + "\nrun: python3 scripts/gen_vendor_confs.py",
                file=sys.stderr,
            )
            return 1
        print("all vendor confs up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
