#!/usr/bin/env python3
# Copyright (c) 2026, BAAI. All rights reserved.
"""Verify, per op, whether the FlagGems Triton path is correct on Ascend.

Every one of the ~390 flagos_python kernels is already compiled into the wheel, so
"can we hook it up" is not a build question -- it is purely whether the gems
kernel runs and matches a CPU reference on this hardware. Static gates cannot
answer that: the DCU port found 26 ops that pass their arity/type checks and then
fail at runtime (required keyword-only `out`, gems asserting a real CUDA tensor,
triton failing to compile, plain wrong numerics). This script establishes the
Ascend equivalent by execution.

Inputs come from PyTorch's own OpInfo sample_inputs, so each op is called the way
aten intends rather than with guessed shapes. Op names are normalized to reach an
OpInfo (strip the aten `_` prefix, drop the inplace `_` suffix, follow aliases).

Each op runs in its own subprocess: a triton compile failure on Ascend can abort
the process rather than raise, which would otherwise lose the whole sweep.

Usage:
  # sweep every candidate (slow -- triton JIT dominates; hours)
  python scripts/verify_flaggems_ascend.py --out /tmp/sweep.json
  # sweep a slice, e.g. to parallelize across devices
  python scripts/verify_flaggems_ascend.py --shard 0/4 --out /tmp/sweep.0.json
  # re-check specific ops
  python scripts/verify_flaggems_ascend.py --ops abs,mul.Tensor,_softmax
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Ops whose gems kernel re-enters torch.<op> for a non-cuda device type, which
# recurses forever on a PrivateUse1 tensor. Established on the CUDA port; the
# recursion is in gems, not in the backend, so it applies here identically.
RECURSIVE = {"mul.Tensor"}


def candidates():
    """Ops with a generated flagos_python kernel that CUDA also routes to gems."""
    disp_to_op = {}
    for line in (REPO / "csrc/aten/generated/ops.cc").read_text().splitlines():
        m = re.search(r'ADD_IMPL_TO_DISPATCHER\(\w+,\s*(\w+),\s*"([^"]+)"', line)
        if m:
            disp_to_op[m.group(1)] = m.group(2)

    have_kernel = set()
    gen = REPO / "csrc/aten/generated/flaggems_python_kernels.cc"
    for line in gen.read_text().splitlines():
        m = re.search(
            r"REGISTER_IMPL_TO_DISPATCHER\(\w+,\s*(\w+),\s*Backend::kFlagGems", line
        )
        if m and m.group(1) in disp_to_op:
            have_kernel.add(disp_to_op[m.group(1)])

    cuda_conf = REPO / "torch_fl/configs/backends_flaggems.conf"
    cuda_py = set()
    for line in cuda_conf.read_text().splitlines():
        line = line.split("#")[0]
        if "=" in line:
            k, v = (x.strip() for x in line.split("=", 1))
            if v == "flagos_python":
                cuda_py.add(k)
    return sorted(have_kernel & cuda_py)


def qualname_map():
    """op name -> the gems qualname its generated kernel calls.

    Read out of the kernel bodies rather than the registrations: the qualname is
    a string literal inside the CallPythonOp_* call, and it is what actually
    gets imported at runtime, so a wrong one (addcdiv_ -> flag_gems.ops.addcdiv_
    .addcdiv_) is only visible here.
    """
    ops_cc = (REPO / "csrc/aten/generated/ops.cc").read_text()
    disp_to_op = dict(
        re.findall(r'ADD_IMPL_TO_DISPATCHER\(\w+,\s*(\w+),\s*"([^"]+)"', ops_cc)
    )
    gen = (REPO / "csrc/aten/generated/flaggems_python_kernels.cc").read_text()
    kern_to_qn, cur = {}, None
    for line in gen.splitlines():
        m = re.match(r"\s*\w[\w:<>,& ]*\s(\w+KernelPython)\(", line)
        if m:
            cur = m.group(1)
        m2 = re.search(r'CallPythonOp_\w+\("([^"]+)"', line)
        if m2 and cur:
            kern_to_qn.setdefault(cur, m2.group(1))
    out = {}
    for disp, kern in re.findall(
        r"REGISTER_IMPL_TO_DISPATCHER\(\w+,\s*(\w+),\s*Backend::kFlagGems,\s*(\w+)\)",
        gen,
    ):
        if disp in disp_to_op and kern in kern_to_qn:
            out[disp_to_op[disp]] = kern_to_qn[kern]
    return out


def write_all_python_conf(path, ops):
    """Conf that inherits the aclnn baseline then forces `ops` to flagos_python.

    The FLAGOS_OP_<op> env override cannot be used for this: common.cc only walks
    ops already present in the table, so the 254 gems ops absent from the Ascend
    baseline are unreachable that way.
    """
    lines = [
        "# AUTO-GENERATED by scripts/verify_flaggems_ascend.py -- do not commit.",
        "include backends_ascend.conf",
    ]
    lines += [f"{op} = flagos_python" for op in ops]
    path.write_text("\n".join(lines) + "\n")


CHILD = r"""
import json, os, sys, warnings
warnings.filterwarnings("ignore")
op_name = sys.argv[1]
res = {"op": op_name}
try:
    import torch, torch_fl  # torch_fl first: installs the torch.npu shim gems reads
    from torch.testing._internal.common_methods_invocations import op_db

    base = op_name.split(".")[0]
    # aten spellings -> OpInfo spellings: private prefix, inplace suffix, aliases.
    cands = [base, base.lstrip("_"), base.rstrip("_"), base.lstrip("_").rstrip("_")]
    info = None
    for o in op_db:
        names = {o.name} | {a.name for a in (getattr(o, "aliases", ()) or ())}
        if names & set(cands):
            info = o
            break
    # Positive control: confirm this op really is routed to flagos_python in the
    # conf we were handed. Without it, any reason the route silently fails to
    # apply (conf overwritten by a concurrent shard, op name not matching the
    # dispatcher key, typo) makes the op run on aclnn and report a clean "ok" --
    # a false pass that looks exactly like a real one.
    conf_txt = open(os.environ["FLAGOS_BACKEND_CONFIG"]).read()
    if f"{op_name} = flagos_python" not in conf_txt:
        res["status"] = "not_routed"
        print(json.dumps(res)); sys.exit(0)

    # Does the qualname the codegen baked in actually resolve? OpInfo drives the
    # functional overload, so routing an inplace/out variant (addcdiv_, log1p.out)
    # can report "ok" while its own kernel was never entered -- and those
    # qualnames are `flag_gems.ops.addcdiv_.addcdiv_` / `...log1p.log1p_out`,
    # neither of which exists. This check is independent of which overload the
    # sample happens to call, so it catches them regardless.
    qn = os.environ.get("VERIFY_QUALNAME", "")
    if qn:
        import importlib

        mod, _, fname = qn.rpartition(".")
        found = False
        try:
            found = hasattr(importlib.import_module(mod), fname)
        except Exception:
            pass
        if not found:
            try:
                import flag_gems

                found = hasattr(flag_gems.ops, fname)
            except Exception:
                pass
        if not found:
            res["status"] = "no_gems_func"
            res["detail"] = qn
            print(json.dumps(res)); sys.exit(0)

    if info is None:
        res["status"] = "no_opinfo"
        print(json.dumps(res)); sys.exit(0)

    samples = list(info.sample_inputs("cpu", torch.float32, requires_grad=False))
    if not samples:
        res["status"] = "no_sample"
        print(json.dumps(res)); sys.exit(0)
    s = samples[0]

    def to_dev(x):
        if isinstance(x, torch.Tensor):
            return x.to("flagos")
        if isinstance(x, (list, tuple)):
            return type(x)(to_dev(v) for v in x)
        if isinstance(x, dict):
            return {k: to_dev(v) for k, v in x.items()}
        return x

    ref = info.op(s.input, *s.args, **s.kwargs)
    got = info.op(to_dev(s.input), *to_dev(s.args), **to_dev(s.kwargs))

    def flat(x):
        if isinstance(x, torch.Tensor):
            return [x]
        if isinstance(x, (list, tuple)):
            return [t for v in x for t in flat(v)]
        return []

    rt, gt = flat(ref), flat(got)
    if len(rt) != len(gt):
        res["status"] = "arity_mismatch"
        print(json.dumps(res)); sys.exit(0)
    worst = 0.0
    for r, g in zip(rt, gt):
        g = g.cpu()
        if r.shape != g.shape:
            res["status"] = "shape_mismatch"
            res["detail"] = f"{tuple(r.shape)} vs {tuple(g.shape)}"
            print(json.dumps(res)); sys.exit(0)
        if r.is_floating_point():
            d = (r.double() - g.double()).abs().max().item()
        else:
            d = 0.0 if torch.equal(r, g) else float("inf")
        worst = max(worst, d)
    res["max_diff"] = worst
    # 2e-2 tolerance: gems kernels run fp32 accumulation differently and Ascend
    # cube ops default to HF32 (cube_math_type=1, ~5e-3 on a K=128 matmul), so a
    # tighter bound would flag precision as breakage. Anything genuinely wrong is
    # orders of magnitude past this.
    res["status"] = "ok" if worst <= 2e-2 else "wrong_numerics"

    # Cross-check: an OpInfo sample can pass while ordinary user code on the same
    # op fails, because OpInfo may reach the op by a different route or supply
    # shapes that miss a branch. Two real cases from the first sweep:
    #   * randn passed via OpInfo but a direct torch.randn(device='flagos') hits
    #     gems' philox helper, which unpacks the generator state as exactly two
    #     int64s and raises ValueError on our CPU-style state.
    #   * mean.dim passed on an inner-dim reduction; dim=0 of a 2D tensor takes
    #     gems' non-inner branch, which calls CUDA APIs via _nvidia heuristics.
    # So re-drive the op through torch.<name> with plain arguments. A failure here
    # is reported even when the OpInfo comparison was clean -- one sample input
    # cannot clear a shape-dependent branch inside a gems kernel.
    if res["status"] == "ok":
        fn = getattr(torch, base.strip("_"), None)
        # Build the probe tensor on CPU and move it: torch.randn(device='flagos')
        # would itself go through the routed gems randn, so every op under test
        # would inherit randn's failure and report it as its own.
        def probe():
            return torch.randn(4, 8).to("flagos")

        # Each probe form is run on CPU first and only counted if CPU accepts it.
        # Without that, the probe reports its own bad arguments as op failures:
        # `cumsum(x, 2)` on a 2D tensor is an invalid call, `clamp(x)` with no
        # bounds is rejected by aten, and `argmax(x, dim=0)` routes to a
        # separately-held overload -- all of which showed up as
        # "direct_call_failed" against ops that are fine.
        #
        # Results are compared to CPU, not merely checked for absence of an
        # exception. isin raised nothing and returned garbage; only a comparison
        # catches that. Two-tensor and tensor+scalar forms are included because
        # a one-tensor-only probe raises TypeError on every call for a
        # two-operand op and skips the check entirely -- which is exactly how
        # isin reached the verified list.
        if fn is not None:
            # Returns None if got matches want, else a short description.
            # (A docstring here would end the CHILD triple-quoted literal.)
            def cmp(want, got):
                wf, gf = flat(want), flat(got)
                if len(wf) != len(gf):
                    return f"arity {len(wf)} vs {len(gf)}"
                # Both sides to CPU before any arithmetic. Comparing two device
                # tensors (the run-to-run check) left the subtraction on device,
                # where `sub` is itself routed to gems and cannot compile an fp64
                # kernel on triton-ascend -- so every op reported the comparison's
                # own CompilationError as its result.
                for w, g in zip(wf, gf):
                    w, g = w.cpu(), g.cpu()
                    if w.shape != g.shape:
                        return f"shape {tuple(w.shape)} vs {tuple(g.shape)}"
                    if w.dtype != g.dtype:
                        return f"dtype {w.dtype} vs {g.dtype}"
                    if w.dtype.is_floating_point:
                        d = (w.double() - g.double()).abs().max().item()
                        if d > 2e-2:
                            return f"max_diff {d:.3g}"
                    elif not torch.equal(w, g):
                        return "unequal"
                return None

            # dim=-1 rather than 0: dim=0 of a 2D tensor lands on the .dim
            # overloads that are separately held back, so it reported routing
            # holes as failures of the op under test.
            forms = [
                (lambda: (torch.randn(4, 8),), {}),
                (lambda: (torch.randn(4, 8),), {"dim": -1}),
                (lambda: (torch.randn(4, 8),), {"dim": -1, "keepdim": True}),
                (lambda: (torch.randn(4, 8), torch.randn(4, 8)), {}),
                (lambda: (torch.randn(4, 8), 2), {}),
            ]
            checked = 0
            for build, kw in forms:
                cpu_args = build()
                try:
                    want = fn(*cpu_args, **kw)
                except Exception:
                    continue  # aten itself rejects this call; not the op's fault
                dev_args = tuple(
                    x.to("flagos") if isinstance(x, torch.Tensor) else x
                    for x in cpu_args
                )
                # Twice: isin returned different answers for identical inputs on
                # separate runs, so a single call can pass a broken kernel.
                try:
                    got = [fn(*dev_args, **kw), fn(*dev_args, **kw)]
                except Exception as e:
                    res["status"] = "direct_call_failed"
                    res["detail"] = f"{type(e).__name__}: {e}"[:300]
                    break
                checked += 1
                bad = cmp(want, got[0]) or cmp(got[0], got[1])
                if bad:
                    res["status"] = "direct_wrong_result"
                    res["detail"] = f"kw={kw} nargs={len(cpu_args)}: {bad}"[:300]
                    break
            if res["status"] == "ok" and checked == 0:
                res["status"] = "ok_probe_skipped"
except Exception as e:
    res["status"] = "raised"
    res["detail"] = f"{type(e).__name__}: {e}"[:300]
print(json.dumps(res))
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    ap.add_argument("--ops", help="comma-separated subset")
    ap.add_argument("--shard", help="i/n -- process only shard i of n")
    ap.add_argument(
        "--also-route",
        help="comma-separated extra ops to route to flagos_python but not test. "
        "An inplace/out variant decomposes to its functional base (clamp_max_ -> "
        "clamp_max.Tensor), and if that base is in neither the aclnn baseline nor "
        "the routed set it raises '<base>: backend not registered' -- which looks "
        "like the tested op is broken when it is really a routing hole.",
    )
    ap.add_argument("--timeout", type=int, default=180)
    args = ap.parse_args()

    ops = args.ops.split(",") if args.ops else candidates()
    if args.shard:
        i, n = (int(x) for x in args.shard.split("/"))
        ops = [o for k, o in enumerate(ops) if k % n == i]

    # Per-process filenames: concurrent shards (one per NPU) would otherwise
    # overwrite each other's conf. A shard reading another's conf silently sees
    # its own ops as absent, so they fall back to aclnn and every one of them
    # reports "ok" -- a false pass across the whole shard, with nothing in the
    # output to show it happened.
    tag = f"{os.getpid()}"
    conf = REPO / f"torch_fl/configs/_verify_sweep_{tag}.conf"
    extra = args.also_route.split(",") if args.also_route else []
    write_all_python_conf(conf, [o for o in ops + extra if o not in RECURSIVE])

    env = dict(os.environ)
    env["FLAGOS_BACKEND_CONFIG"] = str(conf)
    # Per-process Triton cache. Two shards on two devices share ~/.triton/cache
    # by default, and compiling concurrently produced CompilationError on ops
    # (abs, sin, cumsum) that pass cleanly when run alone -- a cache race, not a
    # kernel problem. Getting that wrong marks working ops broken.
    env["TRITON_CACHE_DIR"] = f"/tmp/triton_cache_{tag}"
    child = REPO / f"scripts/_verify_child_{tag}.py"
    child.write_text(CHILD)

    qmap = qualname_map()
    results = []
    t0 = time.time()
    for k, op in enumerate(ops, 1):
        if op in RECURSIVE:
            results.append(
                {"op": op, "status": "recursive", "detail": "gems re-enters torch.<op>"}
            )
        else:
            try:
                p = subprocess.run(
                    [sys.executable, str(child), op],
                    capture_output=True,
                    text=True,
                    env={**env, "VERIFY_QUALNAME": qmap.get(op, "")},
                    timeout=args.timeout,
                    cwd="/tmp",
                )
                line = [ln for ln in p.stdout.splitlines() if ln.startswith("{")]
                if line:
                    results.append(json.loads(line[-1]))
                else:
                    results.append(
                        {
                            "op": op,
                            "status": "crashed",
                            "detail": (p.stderr or "")[-300:],
                        }
                    )
            except subprocess.TimeoutExpired:
                results.append({"op": op, "status": "timeout"})
        r = results[-1]
        print(
            f"[{k}/{len(ops)}] {op:45s} {r['status']:16s} "
            f"{r.get('detail', '') or r.get('max_diff', '')}"[:150],
            flush=True,
        )

    conf.unlink(missing_ok=True)
    child.unlink(missing_ok=True)

    counts = {}
    for r in results:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    print(f"\n=== {len(results)} ops in {time.time() - t0:.0f}s ===")
    for s, c in sorted(counts.items(), key=lambda kv: -kv[1]):
        print(f"  {s:18s} {c}")
    if args.out:
        Path(args.out).write_text(json.dumps(results, indent=1))
        print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
